# Generated by Django 5.0.2 on 2024-03-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('S4S', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgotpassword',
            name='security_answer',
        ),
        migrations.RemoveField(
            model_name='forgotpassword',
            name='security_question',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='security_answer',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='security_question',
        ),
    ]
