# Generated by Django 5.0.2 on 2024-04-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S4S', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
