# Generated by Django 5.0.2 on 2024-04-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('S4S', '0002_comment_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='seen',
        ),
    ]
