# Generated by Django 5.0.2 on 2024-03-29 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S4S', '0002_commentlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlike',
            name='user',
        ),
        migrations.AddField(
            model_name='commentlike',
            name='user_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='S4S.admin'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='user_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='S4S.candidate'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='user_graduate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='S4S.graduate'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='user_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='S4S.student'),
        ),
    ]
