# Generated by Django 5.0.2 on 2024-03-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S4S', '0003_graduate_student_rename_userregistration_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='select_year',
            field=models.IntegerField(),
        ),
    ]
