# Generated by Django 5.0.2 on 2024-03-23 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S4S', '0003_remove_post_likes_post2_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post2',
            old_name='likes',
            new_name='comment_count',
        ),
        migrations.AddField(
            model_name='post2',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='S4S.post2')),
            ],
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
