# Generated by Django 5.0.2 on 2024-03-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S4S', '0003_remove_commentlike_user_commentlike_user_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
