# Generated by Django 5.0.2 on 2024-03-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S4S', '0004_comment_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='has_liked',
            field=models.BooleanField(default=False),
        ),
    ]
