# Generated by Django 5.0.2 on 2024-03-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('S4S', '0005_remove_post2_display_name_remove_post2_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post2',
            name='user_type',
        ),
    ]
