# Generated by Django 5.0.2 on 2024-03-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('S4S', '0005_comment_has_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='has_liked',
        ),
    ]
