# Generated by Django 5.0.2 on 2024-03-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S4S', '0006_remove_post2_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post2',
            name='like_counter',
            field=models.IntegerField(default=0),
        ),
    ]
