# Generated by Django 5.0.2 on 2024-03-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S4S', '0006_post2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post2',
            name='user_name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
