# Generated by Django 5.0.2 on 2024-03-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S4S', '0007_post2_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
