# Generated by Django 5.0.2 on 2024-03-29 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('S4S', '0007_comment_has_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='has_liked',
            new_name='has_liked_comment',
        ),
    ]
