# Generated by Django 5.0.2 on 2024-03-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S4S', '0008_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post2',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
