# Generated by Django 5.0.2 on 2024-03-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('S4S', '0009_post2_like_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post2',
            name='like_counter',
        ),
    ]
