# Generated by Django 5.0.2 on 2024-03-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S4S', '0011_post2_comment_count_post2_dislikes_post2_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post2',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post2',
            name='likes',
        ),
        migrations.AddField(
            model_name='post2',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
